NRP-1910 Installing readable-stream as separate dependency,
in the hopes of resolving problem with
Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
...